modifying the Dockerfile to install isce2 and mintpy via conda-forge

diff --git a/maise/Dockerfile b/maise/Dockerfile
--- a/maise/Dockerfile
+++ b/maise/Dockerfile
@@ -1,76 +1,63 @@
 # using this guide & mambaforge:
-# https://github.com/yunjunz/conda_envs/tree/main/isce2
+# https://github.com/yunjunz/conda_envs
 
-FROM --platform=linux/amd64 docker.io/condaforge/mambaforge:latest
+FROM --platform=linux/amd64 docker.io/condaforge/mambaforge:latest as maise
 
-# easy reference for the software versions (tags or commit hashes) which we're pulling & building
-ENV MINTPY_VERSION=v1.4.1
-ENV ISCE_VERSION=v2.6.1
-ENV PYKML_VERSION=v1.1.0
-ENV PYAPS_VERSION=v0.3.1
-ENV ARIA_VERSION=v1.1.4
+# create new environment & initialize it (adds conda environment stuff to .bashrc)
+RUN mamba create --name maise --yes \
+ && mamba init --system bash
 
-# number of processors used to build
-ARG NPROC=16
+# https://pythonspeed.com/articles/activate-conda-dockerfile/
+# because "each RUN in a Dockerfile is a separate run of bash"
 
-# downloads/checkouts
+# switch shell sh (default in Linux) to bash
+# https://github.com/containers/podman/issues/8477
+# https://stackoverflow.com/questions/55123637/activate-conda-environment-in-docker
+# also make it a login shell so it adds .bashrc before each RUN command
+SHELL ["/bin/bash", "--login", "-o", "pipefail", "-c"]
+RUN echo "mamba activate maise" >> $HOME/.bashrc
+
+# install stuff that's available directory from conda-forge (isce2, mintpy)
+RUN mamba install --name maise --channel conda-forge isce2 mintpy --yes
+
+# check that ISCE_HOME was set in the current environment by the above
+RUN test -n "${ISCE_HOME-}"
+
+# install ARIA-tools
 RUN mkdir -p /tools \
  && cd /tools \
- && git clone --branch $ARIA_VERSION https://github.com/aria-tools/ARIA-tools.git \
- && git clone --branch $MINTPY_VERSION https://github.com/insarlab/MintPy.git \
- && git clone https://github.com/yunjunz/conda_envs.git \
- && mkdir -p isce2; cd isce2 \
- && mkdir -p src build; cd src \
- && git clone --branch $ISCE_VERSION https://github.com/isce-framework/isce2.git
+ && git clone https://github.com/aria-tools/ARIA-tools.git \
+ && mamba install --name maise --channel conda-forge --file /tools/ARIA-tools/requirements.txt --yes \
+ && cd /tools/ARIA-tools \
+ && pip install -e .
 
-# create new environment
-RUN mamba create --name maise --yes \
- && mamba init
-
-RUN echo "source activate maise" > ~/.bashrc
-ENV PATH /opt/conda/envs/maise/bin:$PATH
-
-# install requirements for isce2, MintPy, & ARIA-tools
-RUN cd /tools \
- && mamba install -c conda-forge git pip make --file conda_envs/isce2/requirements.txt --file MintPy/requirements.txt --file ARIA-tools/requirements.txt --yes
-
-# build & install isce2
-RUN cd /tools/isce2/build \
- && cmake /tools/isce2/src/isce2 \
-        -DCMAKE_INSTALL_PREFIX=/tools/isce2/install${ISCE_VERSION} \
-        -DPYTHON_MODULE_DIR="$(python3 -c 'import site; print(site.getsitepackages()[-1])')" \
-        -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} \
-        -DCMAKE_BUILD_TYPE=Release \
- && make -j $NPROC \
- && make install
-
-ENV PYTHONPATH=/tools/isce2/install${ISCE_VERSION}:$PYTHONPATH
-ENV ISCE_HOME=/tools/isce2/src/isce2
-ENV PATH=$ISCE_HOME/applications:$PATH
-
-# build & install MintPy
-RUN cd /tools/MintPy/ \
- && python setup.py install
-
-# build & install ARIA-tools
-RUN cd /tools/ARIA-tools/ \
- && python setup.py install
-
+# install SSARA
 RUN git clone https://www.unavco.org/gitlab/unavco_public/ssara_client.git /tools/SSARA \
  && chmod +x /tools/SSARA/ssara_federated_query.py
 ENV SSARA_HOME=/tools/SSARA
 
-#RUN pip install git+https://github.com/yunjunz/pykml.git@$PYKML_VERSION
-
-RUN pip install git+https://github.com/insarlab/PyAPS.git@$PYAPS_VERSION
+# install PyAPS
+RUN pip install git+https://github.com/insarlab/PyAPS.git
 
 # make everything under /tools/ writable
 RUN chmod -R a+w /tools
 
-# test!
-#RUN topsApp.py --help # topsApp returns 1 on help :/
+
+# run some tests
+
+# debug: check environment
+#RUN env
+
+RUN echo "export PATH=${ISCE_HOME}/bin:${ISCE_HOME}/applications:${PATH}" >> $HOME/.bashrc
+
 RUN topsApp.py --help --steps
 RUN ariaDownload.py --help
 RUN smallbaselineApp.py --help
 RUN /tools/SSARA/ssara_federated_query.py --help
-RUN /tools/isce2/src/isce2/contrib/stack/topsStack/stackSentinel.py --help
+
+# additional stack setup
+# https://github.com/isce-framework/isce2/blob/main/contrib/stack/README.md
+#ISCE_STACK={full_path_to_your_contrib/stack}
+RUN echo "export PYTHONPATH=${PYTHONPATH}:${ISCE_STACK}" >> $HOME/.bashrc
+RUN echo "export PATH=${PATH}:${ISCE_STACK}/topsStack" >> $HOME/.bashrc
+RUN stackSentinel.py --help
